### ISSUE TITLE
Load critical treshold processed wrong. Looks like a copy-paste issue.

### ISSUE THREAD

**Issue by FerencIstvan** [stdevel/check_apcaccess#9]
Hi, I found a small bug:
In the mentioned line, check_value-s last parameters should be options.load_crit instead of options.temp_crit
https://github.com/stdevel/check_apcaccess/blob/88d560f49db519bfc8b20297b0c26952ad50437a/check_apcaccess.py#L106C2-L106C2

Nonetheless, thank you for this project!

**Comment by stdevel** [comment]
Hi @FerencIstvan,
oh, you're right - thanks a lot for pointing out!

Just fixed it - thanks for your feedback. :)
